[project]
name = "debatee"
version = "0.1.0"
description = "debatee using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.108.0,<1.0.0"
]

[project.scripts]
debatee = "debatee.main:run"
run_crew = "debatee.main:run"
train = "debatee.main:train"
replay = "debatee.main:replay"
test = "debatee.main:test"
run_with_trigger = "debatee.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
